### ISSUE TITLE
Matching existing IPS user with a email different than their Discord user fails

### ISSUE THREAD

**Issue by kummitus** [thejhnz/Discord-IPS-Plugin#1]
Hi

My community has experienced some trouble linking accounts, the login handler seems to create new user instead of linking if the email address is different, have you experienced this yet? I think it worked just fine on the version Ahmad sold.

![image](https://user-images.githubusercontent.com/12028179/41060158-6ce892ba-69d7-11e8-9793-d2b764114fbf.png)

**Comment by thejhnz** [comment]
Hi there,

I have noticed some increased amount of 'No Names' coming through. I will need to investigate this.

It appears to be related to emails or usernames that are already in-use.

I don't have an ETA on a fix, if you want to investigate and submit a pull-request I will be open to that.

Cheers

**Comment by thejhnz** [comment]
I have pushed a fix which may fix this issue. Give it a try.

**Comment by thejhnz** [comment]
Appears to be fixed, please update your plugin.

**Comment by kummitus** [comment]
Sweet, thanks a lot!
