### ISSUE TITLE
Getting: 1S111/1 Duplicate entry 'Discord' for key 'PRIMARY'

### ISSUE THREAD

**Issue by ExtrexStudios** [thejhnz/Discord-IPS-Plugin#10]
There isn't a solution to this, i think it has to do with the application it self, i've reinstalled the whole suite (forums) and deleted database twice now and it still happens, i did also download the login_handlers core file thingy which was said here: https://github.com/thejhnz/Discord-IPS-Plugin/issues/4
im not sure what to do to fix this, been trying for an hour to fix it but no succes.

Can anyone help me with this, or is this just a application error and does it have to be fixed by thejhnz?

**Comment by thejhnz** [comment]
I have just pushed a commit that will this installation issue, please give it a try.
