### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Justinh4x** [thejhnz/Discord-IPS-Plugin#2]
Hello,
I've created a folder within the applications folder on my forums folder through my FTP. I've uploaded all the contents of the downloaded file you've provided.
Now what? Typically there's a tar file, I'm sorry that I'm confused but I don't know how to proceed with the installation.

**Comment by thejhnz** [comment]
Inside this zip, is the tar file.


[Discord IPS Plugin.zip](https://github.com/thejhnz/Discord-IPS-Plugin/files/2101529/Discord.IPS.Plugin.zip)

**Comment by DennisL94** [comment]
Invalid application it says for me
