### ISSUE TITLE
One more concern

### ISSUE THREAD

**Issue by Justinh4x** [thejhnz/Discord-IPS-Plugin#3]
Hello, it's me again.
So I have the discord bot on my server and after trying it with the handshake function on the forums I could see they are detected. It's asking me on the settings to add redirect URL's, though I've already done so.

[![Screenshot from Gyazo](https://gyazo.com/fa3b4b4124b0004b5a36c26ab405dc10/raw)](https://gyazo.com/fa3b4b4124b0004b5a36c26ab405dc10)
[![Screenshot from Gyazo](https://gyazo.com/b73b32ca8e173930986a139dca1931c3/raw)](https://gyazo.com/b73b32ca8e173930986a139dca1931c3)

Of course, users can't authenticate and it prompts a "Something went wrong, try again" screen. If someone can help, that would be appreciated.

**Comment by Justinh4x** [comment]
Client Secret, Client ID, Bot Token and the Guild ID are all showing up, so..

**Comment by Justinh4x** [comment]
Can someone please help me out?

**Comment by thejhnz** [comment]
Hi, this message will display even when you have it set. It's an information notice not an error.
