### ISSUE TITLE
Login handler not creating

### ISSUE THREAD

**Issue by RustSociety** [thejhnz/Discord-IPS-Plugin#8]
Reinstalled multiple times and the login handler is not creating itself.

**Comment by rayzone81** [comment]
I've been dealing with the same thing. It worked at first but when I uninstalled it and reinstalled to see if the ban sync would work, the login handler didn't install with it. Don't think we're going to get a response. Guy who created this after groaning that the original author was missing in action is nowhere to be found as well.

**Comment by thejhnz** [comment]
Hi guys,

I have become really busy with a project I am working on. I wanted to upload the version I had working with 4.3.3. I wasn't able to fully test the installation part of the plugin as I was patching and upgrading to make it work with my current installation of 4.3.3.

Happy to merge any pull-requests if you guys are able to sort the issue. I can't give any estimate of when I will be able to look into the issue.

Cheers

**Comment by thejhnz** [comment]
https://github.com/thejhnz/Discord-IPS-Plugin/issues/4 This may help with the install.

**Comment by RustSociety** [comment]
That's not the same issue but since you brought it up I think I see the issue now, when the application is installed it doesn't populate login_settings in core_login_handlers which I think is why it's not showing.

**Comment by theqkash** [comment]
Hey @RustSociety @rayzone81 have you done setting it up or we should install another kind of sotware to make it done?

**Comment by thejhnz** [comment]
I have just pushed a commit that will this installation issue, please give it a try.
